export default [
    {
        path: "/home",
        name: "home",
        label: "首页",
        icon: "HomeOutlined",
        url: "/home/index",
    },
    {
        path: "/screen",
        name: "screen",
        label: "可视化大屏",
        icon: "FundProjectionScreenOutlined",
        url: "/screen/index",
        children: [
            {
                path: "/screen/alarm",
                name: "alarm",
                label: "警报信息",
                icon: "AlertOutlined",
                url: "/screen/alarm",
            },
            {
                path: "/screen/equipment-stats",
                name: "equipmentStats",
                label: "设备统计",
                icon: "BarChartOutlined",
                url: "/screen/equipmentStats",
            },
            {
                path: "/screen/map",
                name: "map",
                label: "地图展示",
                icon: "GlobalOutlined",
                url: "/screen/map",
            },
        ],
    },
    {
        path: "/user",
        name: "user",
        label: "用户管理",
        icon: "UserOutlined",
        url: "/user/index",
    },
    {
        path: "/order",
        name: "order",
        label: "运输订单管理",
        icon: "OrderedListOutlined",
        url: "/order/index",
        children: [
            {
                path: "/order/review",
                name: "review",
                label: "订单审核",
                icon: "AuditOutlined",
                url: "/order/review",
            },
            {
                path: "/order/lease",
                name: "lease",
                label: "租赁订单管理",
                icon: "ShoppingCartOutlined",
                url: "/order/lease",
            },
            {
                path: "/order/monitor",
                name: "monitor",
                label: "实时监控",
                icon: "VideoCameraOutlined",
                url: "/order/monitor",
            },

            {
                path: "/order/tracking",
                name: "tracking",
                label: "订单跟踪",
                icon: "ControlOutlined",
                url: "/order/tracking",
            },
        ],
    },
    {
        path: "/resource",
        name: "resource",
        label: "运输资源管理",
        icon: "DatabaseOutlined",
        url: "/resource/index",
        children: [
            {
                path: "/resource/dispatch",
                name: "dispatch",
                label: "车辆调度管理",
                icon: "ScheduleOutlined",
                url: "/resource/dispatch",
            },
            {
                path: "/resource/equipment",
                name: "equipment",
                label: "冷链设备管理",
                icon: "ToolOutlined",
                url: "/resource/equipment",
            },
            // {
            //     path: "/resource/product",
            //     name: "product",
            //     label: "产品信息管理",
            //     icon: "ContainerOutlined",
            //     url: "/resource/product",
            // },
            // {
            //     path: "/resource/product-trans",
            //     name: "productTrans",
            //     label: "产品运输管理",
            //     icon: "ForkOutlined",
            //     url: "/resource/productTrans",
            // },
            {
                path: "/resource/vehicle",
                name: "vehicle",
                label: "冷链车辆管理",
                icon: "CarOutlined",
                url: "/resource/vehicle",
            },
        ],
    },
]
