export default [
    {
        path: "/home",
        name: "home",
        label: "首页",
        icon: "HomeOutlined",
        url: "/home/index",
    },
    {
        path: "/home/screen",
        name: "screen",
        label: "可视化大屏",
        icon: "FundProjectionScreenOutlined",
        url: "/screen/index",
        children: [
            {
                path: "/home/screen/alarm",
                name: "alarm",
                label: "警报信息",
                icon: "AlertOutlined",
                url: "/screen/alarm",
            },
            {
                path: "/home/screen/equipment-stats",
                name: "equipmentStats",
                label: "设备统计",
                icon: "BarChartOutlined",
                url: "/screen/equipmentStats",
            },
            {
                path: "/home/screen/map",
                name: "map",
                label: "地图展示",
                icon: "GlobalOutlined",
                url: "/screen/map",
            },
        ],
    },
    {
        path: "/home/user",
        name: "user",
        label: "用户管理",
        icon: "UserOutlined",
        url: "/user/index",
    },
    {
        path:"/home/system",
        name:"system",
        label:"系统管理",
        icon:"SettingOutlined",
        url:"/system/index",
        children:[
            {
                path:"/home/system/role",
                name:"role",
                label:"角色管理",
                icon:"UsergroupAddOutlined",
                url:"/system/role",
            },
            {
                path:"/home/system/log",
                name:"log",
                label:"操作日志",
                icon:"FileProtectOutlined",
                url:"/system/log",
            },
        ]
    },
    {
        path: "/home/order",
        name: "order",
        label: "运输订单管理",
        icon: "OrderedListOutlined",
        url: "/order/index",
        children: [
            {
                path: "/home/order/review",
                name: "review",
                label: "订单审核",
                icon: "AuditOutlined",
                url: "/order/review",
            },
            {
                path: "/home/order/lease",
                name: "lease",
                label: "租赁订单管理",
                icon: "ShoppingCartOutlined",
                url: "/order/lease",
            },
            // {
            //     path: "/home/order/monitor",
            //     name: "monitor",
            //     label: "实时监控",
            //     icon: "VideoCameraOutlined",
            //     url: "/order/monitor",
            // },

            // {
            //     path: "/home/order/tracking",
            //     name: "tracking",
            //     label: "订单跟踪",
            //     icon: "ControlOutlined",
            //     url: "/order/tracking",
            // },
        ],
    },
    {
        path: "/home/resource",
        name: "resource",
        label: "运输资源管理",
        icon: "DatabaseOutlined",
        url: "/resource/index",
        children: [
            {
                path: "/home/resource/dispatch",
                name: "dispatch",
                label: "车辆调度管理",
                icon: "ScheduleOutlined",
                url: "/resource/dispatch",
            },
            {
                path: "/home/resource/equipment",
                name: "equipment",
                label: "冷链设备管理",
                icon: "ToolOutlined",
                url: "/resource/equipment",
            },
            // {
            //     path: "/resource/product",
            //     name: "product",
            //     label: "产品信息管理",
            //     icon: "ContainerOutlined",
            //     url: "/resource/product",
            // },
            // {
            //     path: "/resource/product-trans",
            //     name: "productTrans",
            //     label: "产品运输管理",
            //     icon: "ForkOutlined",
            //     url: "/resource/productTrans",
            // },
            {
                path: "/home/resource/vehicle",
                name: "vehicle",
                label: "冷链车辆管理",
                icon: "CarOutlined",
                url: "/resource/vehicle",
            },
        ],
    },
]
